[profile.release]
opt-level = 3
debug = false
strip = true
#debug-assertions = true
overflow-checks = false
lto = true
#panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false
[build]
rustflags = ["-C", "opt-level=3", "-C", "target-cpu=znver3"]
